### ISSUE TITLE
A brief Introduction Please

### ISSUE THREAD

**Issue by hinash88** [mpp-hep/DarkFlow#8]
Hi there,

Can you please add a breif introdution to this repository, what paper have you followed, the commands to follow to run this code easily and about hyper-parameters?

Thank you!

**Comment by PRAkTIKal24** [comment]
Hi, 
This is still a work-in-progress repo. Please check back once the paper is out (soon!). If you'd like updates on when we put the paper out, please follow me on twitter - @PratikJawahar

Cheers!
